#!/usr/bin/bash
conda activate ml-perf-env

#python -m pip install ck --user
#ck pull repo:ck-env
#source activate sean_venv
#source activate selina_kim_venv

#pip install tensorflow or pip install tensorflow-gpu
#pip install onnxruntime or pip install onnxruntime-gpu

#pip install pybind11
sudo apt-get update
sudo dpkg --configure -a
'''
cd $HOME/selina_workspace/inference/loadgen #$HOME/selina_temp_workspace/sima-project/inference/loadgen
CFLAGS="-std=c++14" python setup.py develop --user
cd $HOME/selina_workspace/inference/v0.5/classification_and_detection #$HOME/selina_temp_workspace/sima-project/inference/v0.5/classification_and_detection


python setup.py develop --user


export MODEL_DIR=$HOME/selina_workspace/resnet50v1-5_dir #$HOME/selina_temp_workspace/sima-project/resnet50v1-5_dir
export DATA_DIR=$HOME/CK-TOOLS/dataset-imagenet-ilsvrc2012/validation

#pip install Cython

#pip install opencv-contrib-python

./run_local.sh tf resnet50 gpu 
'''

cd $HOME/sima-mlab/selina_workspace/inference/loadgen #$HOME/selina_temp_workspace/sima-project/inference/loadgen
CFLAGS="-std=c++14" python setup.py develop --user
cd $HOME/sima-mlab/selina_workspace/inference/v0.5/classification_and_detection #$HOME/selina_temp_workspace/sima-project/inference/v0.5/classification_and_detection
python setup.py develop --user
export MODEL_DIR=$HOME/sima-mlab/selina_workspace/resnet50v1-5_dir #$HOME/selina_temp_workspace/sima-project/resnet50v1-5_dir
export DATA_DIR=$HOME/CK-TOOLS/dataset-imagenet-ilsvrc2012/validation

./run_local.sh tf resnet50 gpu
